name: Test, Coverage, and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage-build:
    name: Run Tests, Generate Coverage, and Build
    runs-on: ubuntu-latest  # Use GitHub's free Ubuntu runner

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Cache Maven dependencies to speed up builds

      # Step 3: Run Tests and Generate Coverage
      - name: Run Tests with JaCoCo Coverage
        run: |
          mvn clean verify

      # Step 4: Upload JaCoCo Coverage Report
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

      # Step 5: Build the Application
      - name: Build Application
        run: |
          mvn clean package
          ls -l target/
      
      # Step 6: Upload Build Artifact (JAR file)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloud-libra-jar
          path: target/cloud-libra-1.0-SNAPSHOT.jar
